### ISSUE TITLE
Why the shadow plugin?

### ISSUE THREAD

**Issue by joffrey-bion** [dnault/therapi-runtime-javadoc#13]
It looks like the purpose of the shadow plugin is to build a fat jar. I believe this is only desirable when packaging an end-user application that needs runtime dependencies.
A library, on the other hand, is used within a build system, and its dependencies will be fetched via standard transitive deps resolution.

Is there a particular reason why you're using this plugin for your lib?

**Comment by dnault** [comment]
Packaging an end-user application is certainly one good use of the Shadow plugin. Another is to embed library dependencies in order to avoid dependency conflicts. 

The concern is that a project using therapi-runtime-javadoc may depend on an incompatible version of minimal-json. By repackaging the dependency (not just merging the JARs, but moving the minimal-json classes into a new package) the possibility of conflict is avoided.

Because minimal-json has such a small footprint, the cost of repackaging is low. If we were talking about a huge library like Guava, the tradeoff might not be worth it.
